language: php
php: 
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true

before_install:
    - composer self-update
    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then rm phpunit.xml; fi
    - if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then mv phpunit.hhvm.xml phpunit.xml; fi

script: 
    - phpunit

on_success: always
on_failure: always