language: php
php: 
    - 5.3
    - 5.4
    - 5.6
    - hhvm
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction --dev

script: phpunit

fast_finish: true

on_success: always
on_failure: always